site_name: Ada Lovelace - Khan Academy

site_description: Documentação da Análise de Qualidade sobre o Khan Academy
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_ADA-LOVELACE

nav:
  - Página Inicial: index.md
  - Fase 1:
    - Visão Geral: fase1.md
    - Personas: artefatos/personas.md
    - Especificações dos Requisitos: artefatos/especificacoes.md
    - Quadro de Priorização: artefatos/priorizacao.md
    - Checklist de Qualidade: artefatos/checklist.md
  - Fase 2:
    - GQM: artefatos/fase2/gqm.md
    - Adequação funcional : artefatos/gqm_ad.md
    - Confiabilidade : artefatos/gqm-confiabilidade.md
    - Tabela de Contribuição: artefatos/fase2/tabela-contrib.md
  - Fase 3:
    - Adequação Funcional: artefatos/fase3/adequacao_funcional.md
  - Fase 4:
    - adequacao_funcional: artefatos/fase4/adequacao_funcional4.md
  - Extra: extra.md

theme:
  name: material
  language: pt
  logo: ./images/logo.png
  favicon: ./images/logo.png
  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - toc.integrate
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_ADA-LOVELACE

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - css/custom.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.js
  - js/lightbox-init.js
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

